--------------------------------------------------------
--  DROPS
--------------------------------------------------------
DROP TRIGGER COLLECT_BI_SET_ID;
DROP TRIGGER COLLECT_BI_VALIDATE_ZERO;
DROP TRIGGER COLLECT_BI_SET_COUNTABLE;
DROP TRIGGER COLLECT_BI_CALCULATE_AMOUNT;
DROP TRIGGER COLLECT_BU_VALIDATE_PAYMENT;
DROP TRIGGER PAYMENTDETAIL_BI_SET_ID;
DROP TRIGGER PAYMENTDETAIL_BI_GET_AMOUNT;
DROP TRIGGER PAYMENT_BI_SET_ID;
DROP SEQUENCE PAYMENTDETAIL_SEQ;
DROP SEQUENCE PAYMENT_SEQ;
DROP TABLE PAYMENTDETAIL CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE COLLECT CASCADE CONSTRAINTS;
DROP TABLE COLLECTOR_HARVEST_SEQ CASCADE CONSTRAINTS;
DROP TABLE COLLECT_STATUS_DOMAIN CASCADE CONSTRAINTS;

--------------------------------------------------------
-- SECUENCIAS
--------------------------------------------------------
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE PAYMENTDETAIL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

--------------------------------------------------------
-- TABLA PAYMENT
-- Estructura principal de pago por trabajador
--------------------------------------------------------
CREATE TABLE PAYMENT (
    IDPAYMENT       NUMBER(10,0)  NOT NULL,
    WORKER_CODE     VARCHAR2(6)   NOT NULL,
    DATEPAYMENT     DATE          NOT NULL
);

ALTER TABLE PAYMENT
  ADD CONSTRAINT PAYMENT_PK PRIMARY KEY (IDPAYMENT) ENABLE;

ALTER TABLE PAYMENT
  ADD CONSTRAINT PAYMENT_FK_COLLECTOR 
  FOREIGN KEY (WORKER_CODE)
  REFERENCES COLLECTOR (WORKER_CODE) ENABLE;

--------------------------------------------------------
-- DOMINIO DE ESTADO DE LA RECOLECTA
--------------------------------------------------------
CREATE TABLE COLLECT_STATUS_DOMAIN (
    STATUS_ID   NUMBER       NOT NULL,
    STATUS_NAME VARCHAR2(15) NOT NULL
);

ALTER TABLE COLLECT_STATUS_DOMAIN
  ADD CONSTRAINT COLLECT_STATUS_PK PRIMARY KEY (STATUS_ID) ENABLE;

INSERT INTO COLLECT_STATUS_DOMAIN (STATUS_ID, STATUS_NAME) VALUES (0, 'ZERO');
INSERT INTO COLLECT_STATUS_DOMAIN (STATUS_ID, STATUS_NAME) VALUES (1, 'REGISTRADO');
INSERT INTO COLLECT_STATUS_DOMAIN (STATUS_ID, STATUS_NAME) VALUES (2, 'PAGADO');

--------------------------------------------------------
-- TABLA AUXILIAR: Secuencia de COLLECT por combinación
--------------------------------------------------------
CREATE TABLE COLLECTOR_HARVEST_SEQ (
    WORKER_CODE VARCHAR2(6)   NOT NULL,
    IDPLOT      NUMBER(10,0)  NOT NULL,
    IDHARVEST   NUMBER(10,0)  NOT NULL,
    NEXT_ID     NUMBER(10,0)  NOT NULL,
    CONSTRAINT COLLECTOR_HARVEST_SEQ_PK 
      PRIMARY KEY (WORKER_CODE, IDPLOT, IDHARVEST)
);

--------------------------------------------------------
-- TABLA COLLECT
-- Registro de recolecciones diarias por trabajador
--------------------------------------------------------
CREATE TABLE COLLECT (
    WORKER_CODE     VARCHAR2(6)   NOT NULL,
    IDPLOT          NUMBER(10,0)  NOT NULL,
    IDHARVEST       NUMBER(10,0)  NOT NULL,
    IDCOLLECT       NUMBER(10,0)  NOT NULL,
    COLLECTDATE     DATE          NOT NULL,
    KILOS           NUMBER(10,2)  NOT NULL,
    STATUS_ID       NUMBER        NOT NULL,
    IS_COUNTABLE    NUMBER(1,0)   NOT NULL,
    AMOUNT_TO_PAY   NUMBER(12,2)  NOT NULL
);

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_PK 
  PRIMARY KEY (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_FK_COLLECTOR 
  FOREIGN KEY (WORKER_CODE)
  REFERENCES COLLECTOR (WORKER_CODE) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_FK_HARVEST 
  FOREIGN KEY (IDPLOT, IDHARVEST)
  REFERENCES HARVEST (IDPLOT, IDHARVEST) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_FK_STATUS 
  FOREIGN KEY (STATUS_ID)
  REFERENCES COLLECT_STATUS_DOMAIN (STATUS_ID) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_KILOS 
  CHECK (KILOS >= 0) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_AMOUNT 
  CHECK (AMOUNT_TO_PAY >= 0) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_STATUS 
  CHECK (STATUS_ID IN (0, 1, 2)) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_COUNTABLE 
  CHECK (IS_COUNTABLE IN (0, 1)) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_ZERO_COUNTABLE 
  CHECK (
    (STATUS_ID = 0 AND IS_COUNTABLE = 0) OR 
    (STATUS_ID != 0 AND IS_COUNTABLE = 1)
  ) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_ZERO_KILOS 
  CHECK (
    (STATUS_ID = 0 AND KILOS = 0) OR 
    (STATUS_ID != 0 AND KILOS >= 0)
  ) ENABLE;

ALTER TABLE COLLECT
  ADD CONSTRAINT COLLECT_CHK_ZERO_AMOUNT 
  CHECK (
    (STATUS_ID = 0 AND AMOUNT_TO_PAY = 0) OR 
    (STATUS_ID != 0 AND AMOUNT_TO_PAY >= 0)
  ) ENABLE;

--------------------------------------------------------
-- Índice único: solo un ZERO por asociación
--------------------------------------------------------
CREATE UNIQUE INDEX UNQ_COLLECT_ONE_ZERO
ON COLLECT (
  CASE WHEN STATUS_ID = 0 THEN WORKER_CODE || '-' || IDPLOT || '-' || IDHARVEST END
);

--------------------------------------------------------
-- TABLA PAYMENTDETAIL
--------------------------------------------------------
CREATE TABLE PAYMENTDETAIL (
    IDPAYMENTDETAIL NUMBER(10,0)  NOT NULL,
    IDPAYMENT       NUMBER(10,0)  NOT NULL,
    WORKER_CODE     VARCHAR2(6)   NOT NULL,
    IDPLOT          NUMBER(10,0)  NOT NULL,
    IDHARVEST       NUMBER(10,0)  NOT NULL,
    IDCOLLECT       NUMBER(10,0)  NOT NULL,
    AMOUNT_TO_PAY   NUMBER(12,2)  NOT NULL
);

ALTER TABLE PAYMENTDETAIL
  ADD CONSTRAINT PAYMENTDETAIL_PK 
  PRIMARY KEY (IDPAYMENTDETAIL) ENABLE;

ALTER TABLE PAYMENTDETAIL
  ADD CONSTRAINT PAYMENTDETAIL_FK_PAYMENT
  FOREIGN KEY (IDPAYMENT)
  REFERENCES PAYMENT (IDPAYMENT) ENABLE;

ALTER TABLE PAYMENTDETAIL
  ADD CONSTRAINT PAYMENTDETAIL_FK_COLLECT
  FOREIGN KEY (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT)
  REFERENCES COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT) ENABLE;

ALTER TABLE PAYMENTDETAIL
  ADD CONSTRAINT PAYMENTDETAIL_CHK_AMOUNT 
  CHECK (AMOUNT_TO_PAY >= 0) ENABLE;

--------------------------------------------------------
-- Índice único: Una recolecta solo puede estar en un pago
--------------------------------------------------------
CREATE UNIQUE INDEX UNQ_PAYMENTDETAIL_COLLECT
ON PAYMENTDETAIL (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT);

--------------------------------------------------------
-- TRIGGER: Asignar IDPAYMENT automático
--------------------------------------------------------
CREATE OR REPLACE TRIGGER PAYMENT_BI_SET_ID
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    IF :NEW.IDPAYMENT IS NULL THEN
        :NEW.IDPAYMENT := PAYMENT_SEQ.NEXTVAL;
    END IF;
END;
/
SHOW ERRORS TRIGGER PAYMENT_BI_SET_ID;

--------------------------------------------------------
-- TRIGGER: Asignar IDPAYMENTDETAIL automático
--------------------------------------------------------
CREATE OR REPLACE TRIGGER PAYMENTDETAIL_BI_SET_ID
BEFORE INSERT ON PAYMENTDETAIL
FOR EACH ROW
BEGIN
    IF :NEW.IDPAYMENTDETAIL IS NULL THEN
        :NEW.IDPAYMENTDETAIL := PAYMENTDETAIL_SEQ.NEXTVAL;
    END IF;
END;
/
SHOW ERRORS TRIGGER PAYMENTDETAIL_BI_SET_ID;

--------------------------------------------------------
-- TRIGGER: Asignar IDCOLLECT incremental
--------------------------------------------------------
CREATE OR REPLACE TRIGGER COLLECT_BI_SET_ID
BEFORE INSERT ON COLLECT
FOR EACH ROW
DECLARE
    v_next NUMBER;
BEGIN
    IF :NEW.IDCOLLECT IS NULL THEN
        BEGIN
            SELECT NEXT_ID INTO v_next
              FROM COLLECTOR_HARVEST_SEQ
             WHERE WORKER_CODE = :NEW.WORKER_CODE
               AND IDPLOT = :NEW.IDPLOT
               AND IDHARVEST = :NEW.IDHARVEST
             FOR UPDATE;
            
            :NEW.IDCOLLECT := v_next;
            
            UPDATE COLLECTOR_HARVEST_SEQ
               SET NEXT_ID = v_next + 1
             WHERE WORKER_CODE = :NEW.WORKER_CODE
               AND IDPLOT = :NEW.IDPLOT
               AND IDHARVEST = :NEW.IDHARVEST;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                :NEW.IDCOLLECT := 1;
                INSERT INTO COLLECTOR_HARVEST_SEQ 
                  (WORKER_CODE, IDPLOT, IDHARVEST, NEXT_ID)
                VALUES 
                  (:NEW.WORKER_CODE, :NEW.IDPLOT, :NEW.IDHARVEST, 2);
        END;
    END IF;
END;
/
SHOW ERRORS TRIGGER COLLECT_BI_SET_ID;

--------------------------------------------------------
-- TRIGGER: Establecer IS_COUNTABLE según estado
--------------------------------------------------------
CREATE OR REPLACE TRIGGER COLLECT_BI_SET_COUNTABLE
BEFORE INSERT OR UPDATE OF STATUS_ID ON COLLECT
FOR EACH ROW
BEGIN
    IF :NEW.STATUS_ID = 0 THEN
        :NEW.IS_COUNTABLE := 0;
    ELSE
        :NEW.IS_COUNTABLE := 1;
    END IF;
END;
/
SHOW ERRORS TRIGGER COLLECT_BI_SET_COUNTABLE;

--------------------------------------------------------
-- TRIGGER: Calcular AMOUNT_TO_PAY en COLLECT
--------------------------------------------------------
CREATE OR REPLACE TRIGGER COLLECT_BI_CALCULATE_AMOUNT
BEFORE INSERT OR UPDATE OF KILOS ON COLLECT
FOR EACH ROW
DECLARE
    v_price_per_kilo NUMBER(10,2);
BEGIN
    -- Si es estado ZERO, el monto es 0
    IF :NEW.STATUS_ID = 0 THEN
        :NEW.AMOUNT_TO_PAY := 0;
    ELSE
        -- Obtener precio por kilo de la cosecha
        SELECT H.PRICEPERKILO INTO v_price_per_kilo
          FROM HARVEST H
         WHERE H.IDPLOT = :NEW.IDPLOT
           AND H.IDHARVEST = :NEW.IDHARVEST;
        
        -- Calcular el monto
        :NEW.AMOUNT_TO_PAY := :NEW.KILOS * v_price_per_kilo;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20053,
            'No se encontró información de la cosecha (IDPLOT=' || 
            :NEW.IDPLOT || ', IDHARVEST=' || :NEW.IDHARVEST || ')');
END;
/
SHOW ERRORS TRIGGER COLLECT_BI_CALCULATE_AMOUNT;

--------------------------------------------------------
-- TRIGGER: Validar un solo ZERO por asociación
--------------------------------------------------------
CREATE OR REPLACE TRIGGER COLLECT_BI_VALIDATE_ZERO
BEFORE INSERT OR UPDATE OF STATUS_ID ON COLLECT
FOR EACH ROW
DECLARE
    v_exists NUMBER;
BEGIN
    IF :NEW.STATUS_ID = 0 THEN
        IF INSERTING THEN
            SELECT COUNT(*) INTO v_exists
              FROM COLLECT C
             WHERE C.WORKER_CODE = :NEW.WORKER_CODE
               AND C.IDPLOT = :NEW.IDPLOT
               AND C.IDHARVEST = :NEW.IDHARVEST
               AND C.STATUS_ID = 0;
        ELSE
            SELECT COUNT(*) INTO v_exists
              FROM COLLECT C
             WHERE C.WORKER_CODE = :NEW.WORKER_CODE
               AND C.IDPLOT = :NEW.IDPLOT
               AND C.IDHARVEST = :NEW.IDHARVEST
               AND C.STATUS_ID = 0
               AND C.IDCOLLECT != :NEW.IDCOLLECT;
        END IF;

        IF v_exists > 0 THEN
            RAISE_APPLICATION_ERROR(-20052,
                'Ya existe un registro ZERO para esta asociación. ' ||
                'WORKER_CODE=' || :NEW.WORKER_CODE || 
                ', IDPLOT=' || :NEW.IDPLOT || 
                ', IDHARVEST=' || :NEW.IDHARVEST);
        END IF;
    END IF;
END;
/
SHOW ERRORS TRIGGER COLLECT_BI_VALIDATE_ZERO;

--------------------------------------------------------
-- TRIGGER: Validar recolectas antes de facturar
--------------------------------------------------------
CREATE OR REPLACE TRIGGER COLLECT_BU_VALIDATE_PAYMENT
BEFORE UPDATE OF STATUS_ID ON COLLECT
FOR EACH ROW
DECLARE
    v_detail_exists NUMBER;
BEGIN
    IF :NEW.STATUS_ID = 2 AND :OLD.STATUS_ID = 1 THEN
        SELECT COUNT(*) INTO v_detail_exists
          FROM PAYMENTDETAIL PD
         WHERE PD.WORKER_CODE = :NEW.WORKER_CODE
           AND PD.IDPLOT = :NEW.IDPLOT
           AND PD.IDHARVEST = :NEW.IDHARVEST
           AND PD.IDCOLLECT = :NEW.IDCOLLECT;
        
        IF v_detail_exists = 0 THEN
            RAISE_APPLICATION_ERROR(-20054,
                'No se puede marcar como PAGADO sin detalle de pago asociado');
        END IF;
    END IF;
    
    IF :NEW.STATUS_ID = 0 THEN
        SELECT COUNT(*) INTO v_detail_exists
          FROM PAYMENTDETAIL PD
         WHERE PD.WORKER_CODE = :NEW.WORKER_CODE
           AND PD.IDPLOT = :NEW.IDPLOT
           AND PD.IDHARVEST = :NEW.IDHARVEST
           AND PD.IDCOLLECT = :NEW.IDCOLLECT;
        
        IF v_detail_exists > 0 THEN
            RAISE_APPLICATION_ERROR(-20055,
                'No se puede cambiar a ZERO una recolecta con pago asociado');
        END IF;
    END IF;
END;
/
SHOW ERRORS TRIGGER COLLECT_BU_VALIDATE_PAYMENT;

--------------------------------------------------------
-- TRIGGER: Recuperar AMOUNT_TO_PAY desde COLLECT
--------------------------------------------------------
CREATE OR REPLACE TRIGGER PAYMENTDETAIL_BI_GET_AMOUNT
BEFORE INSERT OR UPDATE ON PAYMENTDETAIL
FOR EACH ROW
DECLARE
    v_amount NUMBER(12,2);
BEGIN
    -- Recuperar el monto calculado desde COLLECT
    SELECT C.AMOUNT_TO_PAY INTO v_amount
      FROM COLLECT C
     WHERE C.WORKER_CODE = :NEW.WORKER_CODE
       AND C.IDPLOT = :NEW.IDPLOT
       AND C.IDHARVEST = :NEW.IDHARVEST
       AND C.IDCOLLECT = :NEW.IDCOLLECT;
    
    :NEW.AMOUNT_TO_PAY := v_amount;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20056,
            'No se encontró la recolecta con WORKER_CODE=' || :NEW.WORKER_CODE ||
            ', IDPLOT=' || :NEW.IDPLOT || 
            ', IDHARVEST=' || :NEW.IDHARVEST ||
            ', IDCOLLECT=' || :NEW.IDCOLLECT);
END;
/
SHOW ERRORS TRIGGER PAYMENTDETAIL_BI_GET_AMOUNT;

--------------------------------------------------------
-- DATOS DE EJEMPLO
--------------------------------------------------------

-- Recolector W00001 en Cosecha (1,3)
INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-01', 0, 0, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-02', 45.50, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-03', 52.30, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-04', 48.75, 1, 0);

-- Primer pago para W00001
INSERT INTO PAYMENT (IDPAYMENT, WORKER_CODE, DATEPAYMENT)
VALUES (NULL, 'W00001', DATE '2024-06-10');

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00001', 1, 3, 2, 0);

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00001', 1, 3, 3, 0);

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00001', 1, 3, 4, 0);

UPDATE COLLECT 
   SET STATUS_ID = 2
 WHERE WORKER_CODE = 'W00001'
   AND IDPLOT = 1
   AND IDHARVEST = 3
   AND IDCOLLECT IN (2, 3, 4);

-- Más recolectas de W00001
INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-11', 55.00, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00001', 1, 3, NULL, DATE '2024-06-12', 60.25, 1, 0);

-- Segundo pago para W00001
INSERT INTO PAYMENT (IDPAYMENT, WORKER_CODE, DATEPAYMENT)
VALUES (NULL, 'W00001', DATE '2024-06-17');

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00001', 1, 3, 5, 0);

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00001', 1, 3, 6, 0);

UPDATE COLLECT 
   SET STATUS_ID = 2
 WHERE WORKER_CODE = 'W00001'
   AND IDPLOT = 1
   AND IDHARVEST = 3
   AND IDCOLLECT IN (5, 6);

-- Recolector W00002 en Cosecha (2,3)
INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00002', 2, 3, NULL, DATE '2025-01-05', 0, 0, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00002', 2, 3, NULL, DATE '2025-01-06', 38.20, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00002', 2, 3, NULL, DATE '2025-01-07', 41.80, 1, 0);

INSERT INTO PAYMENT (IDPAYMENT, WORKER_CODE, DATEPAYMENT)
VALUES (NULL, 'W00002', DATE '2025-01-10');

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00002', 2, 3, 2, 0);

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00002', 2, 3, 3, 0);

UPDATE COLLECT 
   SET STATUS_ID = 2
 WHERE WORKER_CODE = 'W00002'
   AND IDPLOT = 2
   AND IDHARVEST = 3
   AND IDCOLLECT IN (2, 3);

-- Recolector W00003 en Cosecha (1,3)
INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00003', 1, 3, NULL, DATE '2024-06-01', 0, 0, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00003', 1, 3, NULL, DATE '2024-06-02', 55.60, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00003', 1, 3, NULL, DATE '2024-06-03', 49.90, 1, 0);

INSERT INTO PAYMENT (IDPAYMENT, WORKER_CODE, DATEPAYMENT)
VALUES (NULL, 'W00003', DATE '2024-06-08');

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00003', 1, 3, 2, 0);

INSERT INTO PAYMENTDETAIL (IDPAYMENTDETAIL, IDPAYMENT, WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, AMOUNT_TO_PAY)
VALUES (NULL, PAYMENT_SEQ.CURRVAL, 'W00003', 1, 3, 3, 0);

UPDATE COLLECT 
   SET STATUS_ID = 2
 WHERE WORKER_CODE = 'W00003'
   AND IDPLOT = 1
   AND IDHARVEST = 3
   AND IDCOLLECT IN (2, 3);

-- Recolector W00004 en múltiples cosechas
INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00004', 1, 3, NULL, DATE '2024-06-01', 0, 0, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00004', 1, 3, NULL, DATE '2024-06-05', 60.25, 1, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00004', 2, 3, NULL, DATE '2025-01-05', 0, 0, 0);

INSERT INTO COLLECT (WORKER_CODE, IDPLOT, IDHARVEST, IDCOLLECT, COLLECTDATE, KILOS, STATUS_ID, AMOUNT_TO_PAY)
VALUES ('W00004', 2, 3, NULL, DATE '2025-01-08', 44.70, 1, 0);

COMMIT;